services:
  agentv:
    build:
      context: .
      dockerfile: dockerfile
    image: agentv
    container_name: agentv
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge
